services:
  - type: web
    name: phishing-awareness
    env: python
    region: ohio   # 💥 deploy to Ohio region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: LOGIN_PASSWORD
        value: yourAdminPasswordHere
